"""Technology names the fabrication check looks for. If a rewrite names one of these,
it must be in that fact's tools or the allowed skills."""

TECH_TERMS: tuple[str, ...] = (
    # languages
    "Python",
    "Java",
    "JavaScript",
    "TypeScript",
    "Go",
    "Golang",
    "Rust",
    "C++",
    "C#",
    "Scala",
    "Kotlin",
    "Ruby",
    "PHP",
    "SQL",
    "Bash",
    # frameworks
    "FastAPI",
    "Django",
    "Flask",
    "SQLAlchemy",
    "Celery",
    "Spring",
    "Spring Boot",
    "Node.js",
    "Express",
    "React",
    "Angular",
    "Vue",
    "Next.js",
    "NestJS",
    "Rails",
    "Laravel",
    ".NET",
    "gRPC",
    "GraphQL",
    "pandas",
    "NumPy",
    "openpyxl",
    "PySpark",
    "Spark",
    "Airflow",
    "dbt",
    "Kafka",
    "RabbitMQ",
    # AI/ML
    "LLM",
    "LLMs",
    "RAG",
    "OCR",
    "LangChain",
    "LlamaIndex",
    "OpenAI",
    "GPT",
    "Gemini",
    "Claude",
    "Hugging Face",
    "PyTorch",
    "TensorFlow",
    "scikit-learn",
    "Keras",
    "Vector Search",
    "FAISS",
    "Pinecone",
    "Weaviate",
    "Chroma",
    "pgvector",
    "Azure AI Document Intelligence",
    "Textract",
    "Tesseract",
    "GitHub Copilot",
    "Copilot",
    "MLflow",
    "Kubeflow",
    "SageMaker",
    "Vertex AI",
    # data stores
    "MySQL",
    "PostgreSQL",
    "Postgres",
    "OracleDB",
    "Oracle",
    "MongoDB",
    "Redis",
    "Elasticsearch",
    "Cassandra",
    "DynamoDB",
    "SQLite",
    "Snowflake",
    "BigQuery",
    # cloud / infra
    "AWS",
    "AWS S3",
    "S3",
    "Lambda",
    "EC2",
    "ECS",
    "EKS",
    "Azure",
    "Microsoft Azure",
    "GCP",
    "Google Cloud",
    "OCI",
    "OCI Object Storage",
    "Docker",
    "Kubernetes",
    "Terraform",
    "Helm",
    "Jenkins",
    "GitHub Actions",
    "CI/CD",
    "Nginx",
    "Linux",
    # tools / protocols
    "WebSockets",
    "JWT",
    "OAuth",
    "REST",
    "Pytest",
    "Postman",
    "PyInstaller",
    "Qt",
    "Git",
    "Jira",
    "Bitbucket",
    "Bluetooth",
    "GPIO",
    "Salesforce",
    "LeadSquared",
    "Grafana",
    "Prometheus",
)

# Terms that are substrings of others; the longer wins when both match.
ALIASES: dict[str, str] = {
    "llms": "llm",
    "postgres": "postgresql",
    "golang": "go",
    "aws s3": "s3",
    "microsoft azure": "azure",
    "copilot": "github copilot",
    "rest apis": "rest",
}
