"""initial

Revision ID: 48365e0ac198
Revises:
Create Date: 2026-09-27 20:13:20.279756
"""

from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "48365e0ac198"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "answers",
        sa.Column("canonical_question", sa.Text(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("short_answer", sa.String(length=300), nullable=True),
        sa.Column(
            "type",
            sa.Enum("fixed", "rule_based", "personal", "company_specific", name="answer_type"),
            nullable=False,
        ),
        sa.Column(
            "category",
            sa.Enum(
                "logistics",
                "compensation",
                "behavioral",
                "technical",
                "motivation",
                "diversity",
                name="answer_category",
            ),
            nullable=False,
        ),
        sa.Column("times_used", sa.Integer(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_answers")),
    )
    op.create_table(
        "applier_heartbeat",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.String(length=40), nullable=True),
        sa.Column("busy", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_applier_heartbeat")),
    )
    op.create_table(
        "companies",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("aliases", sa.ARRAY(sa.String()), server_default="{}", nullable=False),
        sa.Column("careers_url", sa.Text(), nullable=True),
        sa.Column(
            "platform",
            sa.Enum(
                "greenhouse",
                "lever",
                "ashby",
                "workday",
                "successfactors",
                "darwinbox",
                "oracle",
                "icims",
                "smartrecruiters",
                "own",
                "unknown",
                name="platform",
            ),
            nullable=False,
        ),
        sa.Column("platform_board_id", sa.String(length=200), nullable=True),
        sa.Column("apply_mode", sa.Enum("auto", "quick_apply", name="apply_mode"), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "banking_fintech",
                "services_consulting",
                "product_saas",
                "ai_first",
                name="company_category",
            ),
            nullable=True,
        ),
        sa.Column("tier", sa.Enum("premium", "standard", "services", name="tier"), nullable=False),
        sa.Column(
            "state",
            sa.Enum("candidate", "active", "dormant", "blocked", name="company_state"),
            nullable=False,
        ),
        sa.Column("priority_score", sa.Integer(), nullable=False),
        sa.Column("pinned", sa.Enum("none", "high", "low", name="pinned"), nullable=False),
        sa.Column(
            "source",
            sa.Enum("seed", "email_alert", "pasted_url", "suggested", name="company_source"),
            nullable=False,
        ),
        sa.Column("last_match_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
        sa.UniqueConstraint("name", name=op.f("uq_companies_name")),
    )
    op.create_table(
        "llm_usage",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("requests", sa.Integer(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_usage")),
        sa.UniqueConstraint("day", "provider", name=op.f("uq_llm_usage_day")),
    )
    op.create_table(
        "profile_versions",
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("facts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("resume_template", sa.Text(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profile_versions")),
        sa.UniqueConstraint("version", name=op.f("uq_profile_versions_version")),
    )
    op.create_table(
        "runs",
        sa.Column(
            "kind", sa.Enum("find", "process", "apply", "nightly", name="run_kind"), nullable=False
        ),
        sa.Column("trigger", sa.Enum("schedule", "manual", name="run_trigger"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("running", "ok", "partial", "failed", name="run_status"),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("counts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("llm_requests", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
    )
    op.create_index(
        "uq_runs_one_running_per_kind",
        "runs",
        ["kind"],
        unique=True,
        postgresql_where=sa.text("status = 'running'"),
    )
    op.create_table(
        "settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settings")),
    )
    op.create_table(
        "company_stats_daily",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("jobs_found", sa.Integer(), nullable=False),
        sa.Column("jobs_matched", sa.Integer(), nullable=False),
        sa.Column("jobs_approved", sa.Integer(), nullable=False),
        sa.Column("jobs_applied", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_company_stats_daily_company_id_companies"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company_stats_daily")),
        sa.UniqueConstraint("company_id", "day", name=op.f("uq_company_stats_daily_company_id")),
    )
    op.create_table(
        "jobs",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.String(length=200), nullable=True),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=False),
        sa.Column("dedupe_key", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("location", sa.String(length=300), nullable=False),
        sa.Column(
            "work_mode",
            sa.Enum("hybrid", "remote", "onsite", "unknown", name="work_mode"),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("salary_min_lpa", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("salary_max_lpa", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("experience_min", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("experience_max", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "discovered",
                "filtered_out",
                "error",
                "pending_review",
                "approved",
                "applying",
                "needs_attention",
                "applied",
                "rejected",
                "expired",
                name="job_status",
            ),
            nullable=False,
        ),
        sa.Column("status_reason", sa.Text(), nullable=True),
        sa.Column("fit_score", sa.Integer(), nullable=True),
        sa.Column("fit_summary", sa.Text(), nullable=True),
        sa.Column("fit_gaps", sa.ARRAY(sa.String()), server_default="{}", nullable=False),
        sa.Column("fit_matches", sa.ARRAY(sa.String()), server_default="{}", nullable=False),
        sa.Column("role_focus", sa.Text(), nullable=True),
        sa.Column("flags", sa.ARRAY(sa.String()), server_default="{}", nullable=False),
        sa.Column("expected_ctc_lpa", sa.Numeric(precision=5, scale=1), nullable=True),
        sa.Column("ctc_overridden", sa.Boolean(), nullable=False),
        sa.Column("batch", sa.String(length=40), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmation_path", sa.Text(), nullable=True),
        sa.Column("got_callback", sa.Boolean(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_jobs_company_id_companies")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("canonical_url", name=op.f("uq_jobs_canonical_url")),
        sa.UniqueConstraint("dedupe_key", name=op.f("uq_jobs_dedupe_key")),
    )
    op.create_index("ix_jobs_company_status", "jobs", ["company_id", "status"], unique=False)
    op.create_index("ix_jobs_lease_until", "jobs", ["lease_until"], unique=False)
    op.create_index(
        "ix_jobs_status_score",
        "jobs",
        ["status", sa.literal_column("fit_score DESC")],
        unique=False,
    )
    op.create_table(
        "run_requests",
        sa.Column(
            "kind", sa.Enum("find", "process", "apply", "nightly", name="run_kind"), nullable=False
        ),
        sa.Column("source", sa.Enum("dashboard", "cli", name="request_source"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("waiting", "picked_up", "done", "skipped", name="request_status"),
            nullable=False,
        ),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("picked_up_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], name=op.f("fk_run_requests_run_id_runs")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_requests")),
    )
    op.create_table(
        "application_answers",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("answer_submitted", sa.Text(), nullable=False),
        sa.Column("answer_id", sa.UUID(), nullable=True),
        sa.Column("answer_version", sa.Integer(), nullable=True),
        sa.Column("match_score", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["answer_id"], ["answers.id"], name=op.f("fk_application_answers_answer_id_answers")
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_application_answers_job_id_jobs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_application_answers")),
    )
    op.create_index(
        op.f("ix_application_answers_job_id"), "application_answers", ["job_id"], unique=False
    )
    op.create_table(
        "job_events",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column(
            "from_status",
            sa.Enum(
                "discovered",
                "filtered_out",
                "error",
                "pending_review",
                "approved",
                "applying",
                "needs_attention",
                "applied",
                "rejected",
                "expired",
                name="job_status",
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "discovered",
                "filtered_out",
                "error",
                "pending_review",
                "approved",
                "applying",
                "needs_attention",
                "applied",
                "rejected",
                "expired",
                name="job_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "actor",
            sa.Enum("finder", "processor", "you", "applier", "nightly", "system", name="actor"),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], name=op.f("fk_job_events_job_id_jobs")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_events")),
    )
    op.create_index(op.f("ix_job_events_job_id"), "job_events", ["job_id"], unique=False)
    op.create_table(
        "question_variants",
        sa.Column("answer_id", sa.UUID(), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
        sa.Column("source_job_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["answer_id"], ["answers.id"], name=op.f("fk_question_variants_answer_id_answers")
        ),
        sa.ForeignKeyConstraint(
            ["source_job_id"], ["jobs.id"], name=op.f("fk_question_variants_source_job_id_jobs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_variants")),
    )
    op.create_index(
        op.f("ix_question_variants_answer_id"), "question_variants", ["answer_id"], unique=False
    )
    op.create_index(
        "ix_question_variants_embedding",
        "question_variants",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_table(
        "tailored_documents",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("resume_pdf_path", sa.Text(), nullable=True),
        sa.Column("resume_tex", sa.Text(), nullable=True),
        sa.Column("selection", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("change_summary", sa.Text(), nullable=True),
        sa.Column("cover_letter", sa.Text(), nullable=True),
        sa.Column("fabrication_check", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("profile_version", sa.Integer(), nullable=True),
        sa.Column("prompt_version", sa.String(length=40), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_tailored_documents_job_id_jobs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tailored_documents")),
        sa.UniqueConstraint("job_id", name=op.f("uq_tailored_documents_job_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tailored_documents")
    op.drop_index(
        "ix_question_variants_embedding",
        table_name="question_variants",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_index(op.f("ix_question_variants_answer_id"), table_name="question_variants")
    op.drop_table("question_variants")
    op.drop_index(op.f("ix_job_events_job_id"), table_name="job_events")
    op.drop_table("job_events")
    op.drop_index(op.f("ix_application_answers_job_id"), table_name="application_answers")
    op.drop_table("application_answers")
    op.drop_table("run_requests")
    op.drop_index("ix_jobs_status_score", table_name="jobs")
    op.drop_index("ix_jobs_lease_until", table_name="jobs")
    op.drop_index("ix_jobs_company_status", table_name="jobs")
    op.drop_table("jobs")
    op.drop_table("company_stats_daily")
    op.drop_table("settings")
    op.drop_index(
        "uq_runs_one_running_per_kind",
        table_name="runs",
        postgresql_where=sa.text("status = 'running'"),
    )
    op.drop_table("runs")
    op.drop_table("profile_versions")
    op.drop_table("llm_usage")
    op.drop_table("companies")
    op.drop_table("applier_heartbeat")
    op.drop_table("answers")
    # ### end Alembic commands ###
