"""add manual applications

Revision ID: a9580d22428a
Revises: 48365e0ac198
Create Date: 2026-09-28 20:13:16.745359
"""

from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401
import sqlalchemy as sa
from alembic import op

revision: str = "a9580d22428a"
down_revision: str | None = "48365e0ac198"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "manual_applications",
        sa.Column("company", sa.String(length=200), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column(
            "applied_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum("dashboard", "gmail", name="manual_application_source"),
            nullable=False,
        ),
        sa.Column("gmail_message_id", sa.String(length=100), nullable=True),
        sa.Column("posting_url", sa.Text(), nullable=True),
        sa.Column("resume_pdf_path", sa.Text(), nullable=True),
        sa.Column("cover_letter", sa.Text(), nullable=True),
        sa.Column("got_callback", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_manual_applications")),
        sa.UniqueConstraint(
            "gmail_message_id", name=op.f("uq_manual_applications_gmail_message_id")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("manual_applications")
    # ### end Alembic commands ###
