"""add jobs.apply_url

Revision ID: a519f3de74b0
Revises: a9580d22428a
Create Date: 2026-09-28 21:43:27.243531
"""

from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401
import sqlalchemy as sa
from alembic import op

revision: str = "a519f3de74b0"
down_revision: str | None = "a9580d22428a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("jobs", sa.Column("apply_url", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "apply_url")
    # ### end Alembic commands ###
